apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
    method: fromcode
    another: label
  name: nginx-yaml
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
        - mountPath: /tmp
          name: test-volume
  volume:
   - name: test-volume
     emptDir:
      sizeLimit: 500Mi
